name: GitHub Tiles
description: Generates SVGs for use with your GitHub profile

inputs:
  # Generic
  log-level:
    description: Log level (error, warn, info, debug, trace)
    required: true
    default: info

  # Rust
  token:
    description: GitHub token (https://github.com/settings/tokens/new?scopes=repo,read:user&description=GitHub%20Tiles)
    required: true
  output:
    description: Output directory
    required: false
    default: assets
  tiles:
    description: "Tiles to generate (comma-separated: statistics,languages,contributions)"
    required: false
    default: statistics,languages,contributions
  private:
    description: Include private repositories
    required: false
    default: "false"
  forks:
    description: Include forked repositories
    required: false
    default: "false"
  languages-limit:
    description: Languages to display
    required: false
    default: "5"
  contributions-limit:
    description: Contributions to display
    required: false
    default: "10"
  contributions-min-stars:
    description: Contributions minimum stars
    required: false
    default: "0"
  opaque:
    description: Render opaque background
    required: false
    default: "false"
  optimize:
    description: SVG optimization
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Cache
      id: cache
      uses: actions/cache@v5
      with:
        path: target/release/github-tiles
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.*') }}-${{ hashFiles('**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-github-tiles-

    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: cargo build --release

    - name: Generate SVGs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        RUST_LOG: ${{ inputs.log-level }}
      run: |
        ./target/release/github-tiles \
          --output "${{ inputs.output }}" \
          --tiles "${{ inputs.tiles }}" \
          --private "${{ inputs.private }}" \
          --forks "${{ inputs.forks }}" \
          --languages-limit "${{ inputs.languages-limit }}" \
          --contributions-limit "${{ inputs.contributions-limit }}" \
          --contributions-min-stars "${{ inputs.contributions-min-stars }}" \
          --opaque "${{ inputs.opaque }}" \
          --optimize "${{ inputs.optimize }}"

    - name: Commit
      shell: bash
      run: |
        git add ${{ inputs.output }}/*.svg

        if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name "GitHub Tiles"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update stats"
          git push
        else
          echo "No changes"
        fi
