name: Update Markdown

on:
  schedule:
    - cron: "0 11 * * *"
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@master
        with:
          token: ${{ secrets.USER_TOKEN }}
          template: ./.templates/README.md
          readme: ./README.md

      - name: Update
        shell: bash
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git config user.name "Matthew Wilding"
            git config user.email "mbwilding@gmail.com"
            git add README.md
            git commit -m "Update readme"
            git push
          fi
